_format_version: "1.1"
_workspace: default
services:
- connect_timeout: 60000
  host: httpbin.org
  name: httpbin
  path: /anything
  port: 80
  protocol: http
  read_timeout: 50000
  retries: 5
  write_timeout: 60000
  routes:
  - hosts:
    - example.com
    id: 5fb9e8b8-60e8-4654-a438-8be787ae792c
    path_handling: v1
    preserve_host: false
    protocols:
    - http
    - https
    regex_priority: 0
    strip_path: true
    https_redirect_status_code: 426
